### ISSUE TITLE
Upload within android project structure

### ISSUE THREAD

**Issue by tesYolan** [Kidist-Abraham/GeezKidist#1]
You commited via upload. And that's not okay. The way to doing it with Android studio or from the project root folder by using `git init` and then adding the appropriate files.

**Comment by tesYolan** [comment]
Any updates???

**Comment by Kidist-Abraham** [comment]
This is an old project when i started out learning git, the new repo is at https://github.com/Kidist-Abraham/GeezAlpabetCollector
